imagr_site/imagr_app/urls.py
from django.conf.urls import patterns, url

from imagr_app import views


urlpatterns = patterns('',
    url(r'^$', views.front_page, name='front_page'),
    url(r'^$', views.home_page, name='home_page'),
    url(r'^album/(?P<album_id>\d+)/$', views.album_page, name='album_page'),
    url(r'^photo/(?P<photo_id>\d+)/$', views.photo_page, name='photo_page'),
    url(r'^stream/$', views.stream_page, name='stream_page'),
    url(r'^add_photo/$', views.add_photo, name='add_photo'),
    url(r'^add_album/$', views.add_album, name='add_album'),
    url(r'^delete_photo/(?P<photo_id>\d+)/$', views.delete_photo, name='delete_photo'),
    url(r'^delete_album/(?P<album_id>\d+)/$', views.delete_album, name='delete_album'),
    url(r'^follow/$', views.follow_page, name='follow_page'),
    url(r'^history/$', views.history_page, name='history_page'),

    # url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
)

# url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
# url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
# url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),

imagr_site/imagr_site/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'imagr_site.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^imagr_app/', include('imagr_app.urls', namespace="imagr_app")),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/', include('registration.backends.default.urls')),
)

imagr_site/imagr_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings


# Create your models here.


# After you have that working, you'll also want to create a customized User class:

#     ImagrUser should be based off of the standard built-in Django User, with the following enhancements:
#         Users should be able to follow other users.
#         Users should be able to see a list of the users the follow and the list of users following them.
#         Users should have a 'date_joined' field and an 'active' field that allows disabling an account.
class ImagrUser(AbstractUser):
    following = models.ManyToManyField("self", symmetrical=False, related_name='followers')
    our_date_joined_field = models.DateField(auto_now_add=True)
    our_is_active_field = models.BooleanField(default=False)

#     Photo contains an image and meta-data associated with that image
#         Photos are owned by Users
#         Meta-data should include a title and a description.
#             A date_uploaded, date_modified and date_published field.
#             You should also have a 'published' field takes one of three values ('private', 'shared', 'public')
PUBLISHED_CHOICES = (
    ("private", "Private"),
    ("shared",  "Shared"),
    ("public",  "Public")
)


class Photo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=70)
    description = models.CharField(max_length=300)
    date_uploaded = models.DateField(auto_now_add=True)
    date_modified = models.DateField(auto_now=True)
    date_published = models.DateField(null=True)
    published = models.CharField(max_length=7,
                                choices=PUBLISHED_CHOICES,
                                default="private")
    url = models.CharField(null=True, max_length=150)
    photo_data = models.FileField(null=True, blank=True, max_length=150)

    def __unicode__(self):
        return self.title
#     Album contains Photos and provide meta-data about the collection of photos they contain.
#         Albums are owned by Users
#         Any album can contain many Photos and any Photo may be in more than one Album.
#         Meta-data should include a title and a description. Also a date created, date modified and date published as well as a published field containing the same three options described for Photos
#         Users should be able to designate one contained photo as the 'cover' for the album.
#         The albums created by a user may contain only Photos created by that same user.


class Album(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=300)
    date_uploaded = models.DateField(auto_now_add=True)
    date_modified = models.DateField(auto_now=True)
    date_published = models.DateField(null=True)
    published = models.CharField(max_length=7,
                                choices=PUBLISHED_CHOICES,
                                default="private")
    cover = models.ForeignKey(Photo, related_name='Album_cover')
    photos = models.ManyToManyField(Photo, related_name="Album_photos")

    def __unicode__(self):
        return self.title

imagr_site/imagr_app/forms.py
from django import forms

import models


# PUBLISHED_CHOICES = (
#     ("private", "Private Photo"),
#     ("shared",  "Shared Photo"),
#     ("public",  "Public Photo")
#     )


class CreatePhotoForm(forms.ModelForm):

    class Meta:
        model = models.Photo
        fields = ['title', 'description', 'published', 'image_url']


class CreateAlbumForm(forms.ModelForm):

    class Meta:
        model = models.Album
        fields = ['title', 'description', 'published', 'cover', 'photos']


# Some non-required fields when editing:
class EditPhotoForm(forms.ModelForm):
    title = forms.CharField(max_length=60, required=False)
    description = forms.CharField(max_length=140, required=False)
    image_url = forms.CharField(max_length=1024, required=False)

    class Meta:
        model = models.Photo
        fields = ['title', 'description', 'published', 'image_url']


class EditAlbumForm(forms.ModelForm):
    title = forms.CharField(max_length=60, required=False)
    description = forms.CharField(max_length=140, required=False)

    # Pandora's box...!
    # cover = forms.ModelChoiceField()
    # photos = forms.ModelMultipleChoiceField()

    class Meta:
        model = models.Album
        fields = ['title', 'description', 'published', 'cover', 'photos']

    # def __init__(self, *args, **kwargs):
    #     super(EditAlbumForm, self).__init__(*args, **kwargs)
    #     self.fields['cover'] = forms.ModelChoiceField(queryset=None)
    #     self.fields['photos'] = forms.ModelMultipleChoiceField(queryset=None)


class EditFollowedUsersForm(forms.ModelForm):

    class Meta:
        model = models.ImagrUser
        # Only allow users to alter following on this form.
        fields = ['following']




# class EditPhotoForm(ModelForm):

#     class Meta:
#         model = models.Photo
#         fields = ['title', 'description', 'published', 'image_url']


# class CreatePhotoForm(forms.Form):
#     title = forms.CharField(label='Photo title', max_length=20)
#     description = forms.CharField(label='Photo description', max_length=140)
#     published = forms.ChoiceField(label='Photo publishing', widget=forms.RadioSelect, choices=PUBLISHED_CHOICES)
#     image_url = forms.URLField(label='Image URL', max_length=1024)
#     album = forms.ModelMultipleChoiceField(queryset=models.Album.objects.filter(user=).order_by('-date_uploaded'))


# class CreateAlbumForm:


#     pass

imagr_site/imagr_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.views import generic
from django.shortcuts import get_object_or_404
from models import ImagrUser, Photo, Album
from django.contrib.auth.decorators import login_required
import random
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse
from forms import AlbumForm, PhotoForm, EditPhotoForm, FollowForm
import datetime
# NEW STUFF STARTING HERE
from django.conf import settings
from boto.s3.connection import S3Connection
from boto.s3.key import Key
import mimetypes

def front_page(request):
    if request.user.is_authenticated():
        # This may need to call HttpResponseRequest() instead of render()
        return home_page(request)
    else:
        #We'll fix this later, once we've decided what to do with the front page
        return home_page(request)
        #return HttpResponseRedirect('imagr_app/front_page.html')


@login_required
def home_page(request):
    current_user = get_object_or_404(get_user_model(), pk=request.user.id)
    user_albums = Album.objects.filter(user=current_user.id)
    context = {'current_user': current_user, 'user_albums': user_albums}
    return render(request, 'imagr_app/home_page.html', context)


@login_required
def album_page(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    photos = album.photos.all()
    context = {'album': album, 'photos': photos}
    return render(request, 'imagr_app/album.html', context)


@login_required
def follow_page(request):
    current_user = get_object_or_404(get_user_model(), pk=request.user.id)
    following = current_user.following.all()
    followers = ImagrUser.objects.filter(following=current_user)
    if request.method == 'POST':
        form = FollowForm(request.POST)
        if form.is_valid():
            current_user.following.clear()
            new_friends = form.cleaned_data['following']
            for friend in new_friends:
                current_user.following.add(friend)
            current_user.save()
    else:
        form = FollowForm

    context = {'user': current_user, 'followers': followers, 'following': following, 'follow_form': form}
    return render(request, 'imagr_app/follow_page.html', context)


@login_required
def create_album(request):
    if request.method == 'POST':
        form = AlbumForm(request.POST)
        if form.is_valid():
            new_album = Album.objects.create(
                user=get_object_or_404(get_user_model(), pk=request.user.id),
                title=form.cleaned_data['title'],
                description=form.cleaned_data['description'],
                published=form.cleaned_data['published'],
                date_published=datetime.datetime.now(),
                cover=form.cleaned_data['cover'])
            photos = form.cleaned_data['photos']
            for photo in photos:
                new_album.photos.add(photo)
            new_album.save()
            
            # Need to make this redirect to the album view of the new_album...after I determine all is well so far
            return HttpResponseRedirect(reverse('imagr_app:stream'))
    else:
        form = AlbumForm()

    context = {'album_form': form}
    return render(request, 'imagr_app/create_album.html', context)


@login_required
def edit_album(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    #if album.user != get_user_model():
        #return HttpResponseForbidden()
    if request.method == 'POST':
        form = AlbumForm(request.POST, instance=album)
        if form.is_valid():
            album.title = form.cleaned_data['title']
            album.description = form.cleaned_data['description']
            album.cover = form.cleaned_data['cover']
            album.photos.clear()
        photos = form.cleaned_data['photos']
        for photo in photos:
            print album
            album.photos.add(photo)
        album.save()
        return HttpResponseRedirect(reverse('imagr_app:stream'))

    else:
        form = AlbumForm()

    context = {'album_form': form}
    return render(request, 'imagr_app/edit_album.html', context)


@login_required
def photo_page(request, photo_id):
    photo = get_object_or_404(Photo, pk=photo_id)
    context = {'photo': photo}
    return render(request, 'imagr_app/photo.html', context)


@login_required
def upload_photo(request):

    def store_in_s3(filename, content):
        """stores uploaded image to S3"""
        conn = S3Connection(settings.ACCESS_KEY_ID, settings.SECRET_ACCESS_KEY)
        bucket = conn.get_bucket("imagr.app.codefellows")
        mime = mimetypes.guess_type(filename)
        key = Key(bucket)
        key.key = filename
        key.set_metadata("Content-Type", mime)
        key.set_contents_from_file(content)
        key.set_acl("public-read")

    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            # Grab the photo data here, to store on S3
            photo = request.FILES['photo_data']
            filename = photo.name
            content = photo.file
            store_in_s3(filename, content)
            new_photo = Photo.objects.create(
                user=get_object_or_404(get_user_model(), pk=request.user.id),
                title=form.cleaned_data['title'],
                description=form.cleaned_data['description'],
                published=form.cleaned_data['published'],
                date_published=datetime.datetime.now(),
                photo_data=form.cleaned_data['photo_data'],
                url="https://s3-us-west-2.amazonaws.com/imagr.app.codefellows/" + filename
                )
            new_photo.save()

            return HttpResponseRedirect(reverse('imagr_app:stream'))
    else:
        form = PhotoForm()
    
    context = {'photo_form': form}
    return render(request, 'imagr_app/submit_photo.html', context)


@login_required
def edit_photo(request, photo_id):
    photo = get_object_or_404(Photo, pk=photo_id)
    if request.method == 'POST':
        form = PhotoForm(request.POST, instance=photo)
        if form.is_valid():
            photo.title = form.cleaned_data['title']
            photo.description = form.cleaned_data['description']
        photo.save()
        return HttpResponseRedirect(reverse('imagr_app:stream'))

    else:
        form = EditPhotoForm()

    context = {'photo_form': form, 'photo': photo}
    return render(request, 'imagr_app/edit_photo.html', context)


@login_required
def stream(request):
    recent_user_photos = Photo.objects.filter(user=request.user.id).order_by('-date_uploaded')[:4]
    recent_friend_photos = []

    for photo in Photo.objects.exclude(published="private").order_by('-date_uploaded')[:4]:
        for follower in photo.user.followers.all():
            if request.user.id == follower.id:
                recent_friend_photos.append(photo)

    photos_to_stream = random.sample(recent_friend_photos, min(len(recent_friend_photos), 4))
    context = {'friends_photos': photos_to_stream, 'user_photos': recent_user_photos}

    return render(request, 'imagr_app/stream.html', context)

imagr_site/imagr_app/templates/imagr_app/add_album.html
{% extends "imagr_app/base.html" %}
{% block body %}
<h1>Make new album</h1>

<h3>Missing or invalid entries will helpfully reset the form.</h3>
<br>

{{ context_string }}

<form method="post" action="">
    {% csrf_token %}
    {{ album_form }}
    <br><br>
    <input type="submit" value="Make Album!">
</form>


<br>
{% endblock %}

imagr_site/imagr_app/templates/imagr_app/add_photo.html
{% extends "imagr_app/base.html" %}
{% block body %}
<h1>Add new photo</h1>

<h3>Missing or invalid entries will helpfully reset the form.</h3><br>

{{ context_string }}

<form method="post" action="">
    {% csrf_token %}
    {{ photo_form }}
    <br><br>
    <input type="submit" value="Add Photo!">
</form>


<br>
{% endblock %}

imagr_site/imagr_app/templates/imagr_app/album_page.html
{% extends "imagr_app/base.html" %}
{% block body %}
<h3>Album Details Page</h3>

{% if this_album %}

    {% if this_album.cover %}
        <h3>Album Cover:</h3><a href="{% url 'imagr_app:photo_page' this_album.cover.id %}"><img src="{{ this_album.cover.image_url }}"></a>
        <h3>Album Title:</h3>
        <h1>{{ this_album.title }}</h1>
        <h3>Album Description:</h3>
        <p>{{ this_album.description }}</p>
    {% endif %}

    {% if list_of_photos %}
        <h3>Album Contents:</h3>
        <ul>
        {% for photo in list_of_photos %}
            <a href="{% url 'imagr_app:photo_page' photo.id %}"><img src="{{ photo.image_url }}"></a>
            <br>
            <a href="{% url 'imagr_app:photo_page' photo.id %}">{{ photo.title }}</a>
            <br><br>
        {% endfor %}
        </ul>
    {% else %}
        <p>There aren't any photos in this album.</p>
    {% endif %}

    {% if this_album_edit_form %}
        <br>
        <h3>Edit Album:</h3>
        <br>
        {% if context_string %}
            <h2>{{ context_string }}</h2>
            <br>
        {% endif %}
        <form method="post" action="">
            {% csrf_token %}
            {{ this_album_edit_form }}
            <br><br>
            <input type="submit" value="Edit Album">
        </form>

    {% endif %}
    <br>
    <form action="{% url 'imagr_app:delete_album' this_album.id %}">
        {% csrf_token %}
        <input type="submit" value="Delete Album">
    </form>
{% else %}
    <p>Album #{{ this_album.id }} not found.</p>
    <br>
    <br>


{% endif %}
{% endblock %}

imagr_site/imagr_app/templates/imagr_app/base.html
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}{{ site_title|default:_('Imagr, the open photo link sharing site') }}{% endblock %}</title>
{% block branding %}
<h1 id="site-name"><a href="{% url 'imagr_app:front_page' %}">Imagr</a></h1>
{% endblock %}
User: <strong>{% firstof user.get_short_name user.get_username %}</strong>
<br>
{% block nav-global %}
    <a href="/accounts/login">Log In</a> |
    <a href="/accounts/logout">Log Out</a> |
    <a href="{% url 'imagr_app:stream_page' %}">Your Stream</a> |
    <a href="{% url 'imagr_app:history_page' %}">Your History</a> |
    <a href="{% url 'imagr_app:add_photo' %}">Add Photo</a> |
    <a href="{% url 'imagr_app:add_album' %}">Add Album</a> |
    <a href="{% url 'imagr_app:follow_page' %}">Following</a>
{% endblock %}
<hr>
</head>
<body>

{% block body %}{% endblock %}

{% comment %}
Also including a content block so it works smoothly
    with the default registration templates.
{% endcomment %}
{% block content %}{% endblock %}
</body>
</html>

imagr_site/imagr_app/templates/imagr_app/create_album.html
<h1>Create New Album</h1>

<form method="post", action="">
    {% csrf_token %}
    {{ album_form }}
    <br><br>
    <input type="submit" value="Create Album">
</form>

<br>
<a href="{% url 'imagr_app:front_page' %}">Back to HomePage</a>

imagr_site/imagr_app/templates/imagr_app/edit_album.html
<h1>Edit Album</h1>
{% if album_form %}
<form method="post", action="">
    {% csrf_token %}
    {{ album_form }}
    <br><br>
    <input type="submit" value="Edit Album">
</form>
{% else %}
    <p>No form, son</p>
{% endif %}
<br>
<a href="{% url 'imagr_app:front_page' %}">Back to HomePage</a>

imagr_site/imagr_app/templates/imagr_app/edit_photo.html
<h1>Edit Photo</h1>
{% if photo_form %}
<h2>{{ photo.title }}</h2>
<img class="photo" src="{{ photo.url }}" width="450" height="300">
<form method="post", action="">
    {% csrf_token %}
    {{ photo_form }}
    <br><br>
    <input type="submit" value="Edit Photo">
</form>
{% else %}
    <p>Could not find the specified photo</p>
{% endif %}
<br><br>
<a href="{% url 'imagr_app:front_page' %}">Home</a>

imagr_site/imagr_app/templates/imagr_app/history_page.html
{% extends "imagr_app/base.html" %}
{% block body %}
<h1>History Page</h1>

{% if list_of_albums %}
    <ul>
    <h1>Your Album History</h1>
    {% for album in list_of_albums %}
        <!-- stripping the hrefs makes this page successfully display
        the image stored in the photo referenced by the album's cover
        link; in other words, the <img src= ... album.cover.image_url ... >
        part WORKS on its own. -->
        <li><a href="{% url 'imagr_app:album_page' album.id %}"><img src="{{ album.cover.image_url }}" height="128" width="128"></a></li>
        <li><a href="{% url 'imagr_app:album_page' album.id %}">{{ album.title }}</a> : Date uploaded: {{ album.date_uploaded }}</li>
        <li>{{ album.description }}</li>

    {% endfor %}
    </ul>
{% else %}
    <p>You haven't made any albums yet.</p>
{% endif %}
<br>
{% if list_of_photos %}
    <ul>
    <h1>Your Photo History</h1>
    {% for photo in list_of_photos %}
        <!-- stripping the hrefs makes this page successfully display
        the image stored in the photo referenced by the album's cover
        link; in other words, the <img src= ... album.cover.image_url ... >
        part WORKS on its own. -->
        <li><a href="{% url 'imagr_app:photo_page' photo.id %}"><img src="{{ photo.image_url }}" height="128" width="128"></a></li>
        <li><a href="{% url 'imagr_app:photo_page' photo.id %}">{{ photo.title }}</a> : Date uploaded: {{ photo.date_uploaded }}</li>
        <li>{{ photo.description }}</li>

    {% endfor %}
    </ul>
{% else %}
    <p>You haven't submitted any photos yet.</p>

{% endif %}

{% endblock %}

imagr_site/imagr_app/templates/imagr_app/login.html
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

imagr_site/imagr_app/templates/imagr_app/photo.html
{% if photo %}
    <h2>{{ photo.title }}<a href="{% url 'imagr_app:edit_photo' photo.id %}"> Edit</a></h2>
    <img class="photo" src="{{ photo.url }}" width="450" height="300">
    <p>{{ photo.description }}</p>
{% else %}
    <p>Could not find the specified photo</p>
{% endif %}
<br><br>
<a href="{% url 'imagr_app:front_page' %}">Home</a>

imagr_site/imagr_app/templates/imagr_app/photo_page.html
{% extends "imagr_app/base.html" %}
{% block body %}
<h3>Photo Details Page</h3>

{% if this_photo %}
    <h3>Photo:</h3>
    <img src="{{ this_photo.image_url }}">
    <br>
    <h3>Title:</h3>
    {{ this_photo.title }}
    <br>
    <h3>Description:</h3>
    {{ this_photo.description }}
    <br>
    <br>
    {% if this_photo_edit_form %}
        <br>
        <h3>Edit Photo:</h3>
        <br>
        {% if context_string %}
            <br>
            <h2>{{ context_string }}</h2>
            <br>
        {% endif %}
        <form method="post" action="">
            {% csrf_token %}
            {{ this_photo_edit_form }}
            <br><br>
            <input type="submit" value="Edit Photo">
        </form>

    {% endif %}
    <br>
    <form action="{% url 'imagr_app:delete_photo' this_photo.id %}">
        {% csrf_token %}
        <input type="submit" value="Delete Photo">
    </form>


{% else %}
    <p>Photo #{{ this_photo.id }} not found at {{ this_photo.image_url }}.</p>
{% endif %}
{% endblock %}

imagr_site/imagr_app/templates/imagr_app/stream.html
{% if user_photos %}
    <h3>Your recent photos</h3>
    <ul>
    {% for photo in user_photos %}
        <br>
        <a href="{% url 'imagr_app:photo_page' photo.id %}">{{ photo.title }}</a><br>
        <img class="photo" src="{{ photo.url }}" width="150" height="100">
    {% endfor %}
    </ul>
{% else %}
    <p>You don't have any recent photos</p>
{% endif %}
{% if friends_photos %}
    <h3>Recent photos by friends</h3>
    <ul>
    {% for photo in friends_photos %}
        <a href="{% url 'imagr_app:photo_page' photo.id %}">{{ photo.title }}</a>
        <br>
    <br><br>
    {% endfor %}
{% endif %}
<a href="{% url 'imagr_app:front_page' %}">Home</a>

imagr_site/imagr_app/templates/imagr_app/stream_page.html
{% extends "imagr_app/base.html" %}
{% block body %}
{% if recent_self_photos %}
    <h3>Your Recent Photos:</h3>
    <ul>
    {% for photo in recent_self_photos %}
        <a href="{% url 'imagr_app:photo_page' photo.id %}"><img src="{{ photo.image_url }}"></a>
        <br>
        <a href="{% url 'imagr_app:photo_page' photo.id %}">{{ photo.title }}</a>
        <br><br>
    {% endfor %}
    </ul>
{% else %}
    <p>You don't have any recent photos.</p>
{% endif %}
{% if recent_friend_photos %}
    <h3>Friends' Recent Photos:</h3>
    <ul>
    {% for friend_photo in recent_friend_photos %}
        <a href="{% url 'imagr_app:photo_page' friend_photo.id %}"><img src="{{ friend_photo.image_url }}"></a>
        <br>
        <a href="{% url 'imagr_app:photo_page' friend_photo.id %}">{{ friend_photo.title }}</a>
        <br><br>
    {% endfor %}
    </ul>
{% else %}
    <p>Your friends don't have any recent photos.</p>
{% endif %}
{% endblock %}

imagr_site/imagr_app/templates/imagr_app/submit_photo.html
<h1>Add new photo</h1>

<form enctype="multipart/form-data" method="post" action="">
    {% csrf_token %}
    {{ photo_form }}
    <br><br>
    <input type="submit" value="Upload Photo">
</form>

<br>
<a href={% url 'imagr_app:front_page' %}>Back to Homepage</a>